# 路由配置
from handlers.api import *
from handlers.admin import weblogs

handlers = [(r'/api/register', user.RegisterHandler),
            (r'/api/login', user.LoginHandler),
            (r'/api/autoLogin', user.AutoLoginHandler),
            (r'/api/logout', user.LogoutHandler),
            (r'/api/getCommonInfo', public.CommonInfoHandler),
            (r'/api/getDepartments', public.DepartmentsHandler),
            (r'/api/user/currentUser', user.CurrentUserHandler),
            (r'/api/user/activities', user.ActivitiesHandler),
            (r'/api/user/notices', user.NoticesHandler),
            (r'/api/user/navLink/(\w+)', user.CustomNavHandler),
            (r'/api/chart/toolStatistics', chart.ChartDataHandler),
            (r'/api/chart/performance', chart.PerformanceHandler),
            (r'/api/chart/performance/(\w+)', chart.PerformanceHandler),
            (r'/api/chart/autoTest/(\w+)/(\w+)', chart.AutoTestHandler),
            (r'/api/group/getTeams', members.DepartmentsEdit),
            (r'/api/group/editTeams/(\w+)', members.DepartmentsEdit),
            (r'/api/project/getProjects', dashboard.ProjectsHandler),
            (r'/api/project/editProjects/(\w+)', dashboard.ProjectsHandler),
            (r'/api/config/system', dashboard.SystemConfigHandler),
            (r'/api/upload/(\w+)/(\w+)', public.UploadFiles),
            (r'/api/activeUser', user.ActiveUserHandler),
            (r'/api/test/gui/(\w+)/(\w+)', gui_test_manger.GUITestHandler),
            (r'/api/test/api/(\w+)/(\w+)', api_test_manger.APITestHandler),
            (r'/api/test/token/(\w+)/(\w+)', api_test_manger.TestAPIHandler),
            (r'/api/env/(\w+)/(\w+)', dashboard.EnvironmentManage),
            (r'/api/tools/shell/(\w+)', tools.RunShellHandler),
            (r'/api/tools/sql/(\w+)', tools.RunSQLHandler),
            (r'/api/tools/diff/(\w+)', tools.PackageDiff),
            (r'/api/tools/getTools/(\w+)', tools.ToolsHandler),
            (r'/api/tools/editTools/(\w+)', tools.ToolsHandler),
            (r'/api/knowledge/(\w+)/(\w+)', knowledge.KnowledgeHandler),
            (r'/api/syncdb/(\w+)', tools.SyncDB),
            (r'/api/mail/(\w+)', public.SendMailHandler),
            (r'/api/ws/weblogs', weblogs.WeblogsHandler),
            (r'/api/jacoco/reports', chart.JacocoReports),
            (r'/api/jenkins/(\w+)', gui_test_manger.JenkinsHandler)]
