'\" t
.\"     Title: \fBmysqlfailover\fR
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 01/14/2017
.\"    Manual: MySQL Utilities
.\"    Source: MySQL 1.6.4
.\"  Language: English
.\"
.TH "\FBMYSQLFAILOVER\FR" "1" "01/14/2017" "MySQL 1\&.6\&.4" "MySQL Utilities"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mysqlfailover \- Automatic replication master failover
.SH "SYNOPSIS"
.HP \w'\fBmysqlfailover\ [\fR\fB\fIoptions\fR\fR\fB]\fR\ 'u
\fBmysqlfailover [\fR\fB\fIoptions\fR\fR\fB]\fR
.SH "DESCRIPTION"
.PP
This utility permits users to perform replication health monitoring and automatic failover on a replication topology consisting of a single master and its slaves\&. The utility is designed to run interactively or continuously refreshing the health information and checking the master status at periodic intervals\&. Its primary mission is to monitor the master for failure and when a failure occurs, execute failover to one of the slaves that is in a valid state\&. The utility accepts an optional list of slaves to be considered for the candidate slave\&.
.PP
This utility is designed to work exclusively for servers that support global transaction identifiers (GTIDs) and have
gtid_mode=ON\&. MySQL server versions 5\&.6\&.5 and higher support GTIDs\&. See
\m[blue]\fBReplication with Global Transaction Identifiers\fR\m[]\&\s-2\u[1]\d\s+2
for more information\&. Thus, this utility does not work with anonymous replication servers (binary log + position)\&.
.PP
The user can specify the interval in seconds to use for detecting the master status and generating the health report using the
\fB\-\-interval\fR
option\&. At each interval, the utility checks to see if the server is alive via a ping operation followed by a check of the connector to detect if the server is still reachable\&. The ping operation can be controlled with the
\fB\-\-ping\fR
option (see below)\&.
.PP
If the master is found to be offline or unreachable, the utility executes one of the following actions based on the
\fB\-\-failover\-mode\fR
option value\&. The available values are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBauto\fR
(default): Execute automatic failover to the list of candidates first and if no slaves are viable, continue to search the remaining slaves for a viable candidate\&. The command tests each candidate slave listed for the prerequisites\&. Once a candidate slave is elected, it is made a slave of each of the other slaves thereby collecting any transactions executed on other slaves but not the candidate\&. In this way, the candidate becomes the most up\-to\-date slave\&. If no slave is found to be a viable candidate, the utility generates an error and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBelect\fR: This mode is the same as auto, except if no candidates specified in the list of candidate slaves are viable, then it does not check the remaining slaves, and instead generates an error and then exits\&. Use this option to force failover to one or more specific slaves using the
\fB\-\-candidates\fR
option\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBfail\fR: This mode produces an error and does not failover when the master is detected as down or unreachable\&. This mode is used to provide periodic health monitoring without the failover action taken\&.
.RE
.PP
For all options that permit specifying multiple servers, the options require a comma\-separated list of connection parameters in the following form (where the password, port, and socket are optional)\&.:
.sp
.if n \{\
.RS 4
.\}
.nf
\fI*user*\fR[:\fI*passwd*\fR]@\fI*host*\fR[:\fI*port*\fR][:\fI*socket*\fR] or
\fI*login\-path*\fR[:\fI*port*\fR][:\fI*socket*\fR]
.fi
.if n \{\
.RE
.\}
.PP
The utility permits users to discover slaves connected to the master\&. The discover slaves feature is run automatically on each interval\&. Furthermore, it is required that slaves use the \-\-master\-info\-repository=TABLE startup setting\&.
.PP
The discover slaves option
\fBrequires\fR
all slaves use the
\-\-report\-host
and
\-\-report\-port
server startup variables with the correct hostname and port\&. If these are missing or report the incorrect information, the slave may not be detected and thus not included in the operation of the utility\&. The discover slaves option ignores any slaves to which it cannot connect\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
If you have one or more slaves which do not report their hostname and port and should a failover event occur, those slaves are not included in the resulting topology\&. That is, they are not a slave of the new master\&. Be sure to check that all of your slaves are accounted for in the health report before relying on the utility for complete automatic failover\&.
.sp .5v
.RE
.PP
The utility permits the user to specify an external script to execute before and after the switchover and failover commands\&. The user can specify these with the
\fB\-\-exec\-before\fR
and
\fB\-\-exec\-after\fR
options\&. The return code of the script is used to determine success\&. Each script must report 0 (success) to be considered successful\&. If a script returns a value other than 0, the result code is presented in an error message\&.
.PP
The utility also permits the user to specify a script to be used for detecting a downed master or an application\-level event to trigger failover\&. This can be specified using the
\fB\-\-exec\-fail\-check\fR
option\&. The return code for the script is used to invoke failover\&. A return code of 0 indicates failover should not take place\&. A return code other than 0 indicates failover should take place\&. This is checked at the start of each interval if a script is supplied\&. The timeout option is not used in this case and the script is run once at the start of each interval\&.
.PP
The utility permits the user to log all actions taken during the commands\&. The
\fB\-\-log\fR
option requires a valid path and filename of the file to use for logging operations\&. The log is active only when this option is specified\&. The option
\fB\-\-log\-age\fR
specifies the age in days that log entries are kept\&. The default is seven (7) days\&. Older entries are automatically deleted from the log file (but only if the
\fB\-\-log\fR
option is specified)\&.
.PP
The format of the log file includes the date and time of the event, the level of the event (informational \- INFO, warning \- WARN, error \- ERROR, critical failure \- CRITICAL), and the message reported by the utility\&.
.PP
The interface provides a number of options for displaying additional information\&. You can choose to view the replication health report (default), or choose to view the list of GTIDs in use, the UUIDs in use, or view the log file contents if logging is enabled\&. Each of these reports is described below\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBhealth\fR
Display the replication health of the topology\&. This report is the default view for the interface\&. By default, this includes the host name, port, role (MASTER or SLAVE) of the server, state of the server (UP = is connected, WARN = not connected but can ping, DOWN = not connected and cannot ping), the GTID_MODE, and health state\&.
.sp
The master health state is based on the following: if GTID_MODE=ON, the server must have the binary log enabled, and a user must exist with the REPLICATE SLAVE privilege\&.
.sp
The
\fB\-\-seconds\-behind\fR
option is used to detect when a slave is behind the master\&. It allows users to set a threshold for reporting purposes only\&. It does not apply to slave candidacy or selection during failover\&.
.sp
The slave health state is based on the following: the IO_THREAD and SQL_THREADS must be running, it must be connected to the master, there are no errors, the slave delay for non\-GTID enabled scenarios is not more than the threshold provided by the
\fB\-\-max\-position\fR
and the slave is reading the correct master log file, and slave delay is not more than the
\fB\-\-seconds\-behind\fR
threshold option\&.
.sp
At each interval, if the discover slaves option was specified at startup and new slaves are discovered, the health report is refreshed\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBgtid\fR: Display the master\*(Aqs list of executed GTIDs, contents of the GTID variables;
@@GLOBAL\&.GTID_EXECUTED,
@@GLOBAL\&.GTID_PURGED, and
@@GLOBAL\&.GTID_OWNED\&. Thus, you can toggle through the four screens by pressing the \*(AqG\*(Aq key\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBUUID\fR: Display universally unique identifiers (UUIDs) for all servers\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBLog\fR: This option displays the contents of the log file, which only visible if the
\fB\-\-log\fR
option is specified\&. This can be helpful to see when failover occurred, and which actions or messages were recorded at the time\&.
.RE
.PP
The user interface is designed to match the size of the terminal window in which it is run\&. A refresh option is provided to permit users to resize their terminal windows or refresh the display at any time\&. However, the interface automatically resizes to the terminal window on each interval\&.
.PP
The interface displays the name of the utility, the master\*(Aqs status including binary log file, position, and filters as well as the date and time of the next interval event\&.
.PP
The interface also permits the user to scroll up or down through a list longer than what the terminal window permits\&. When a long list is presented, the scroll options become enabled\&. The user can scroll the list up with the up arrow key and down with the down arrow key\&.
.PP
Use the
\fB\-\-verbose\fR
option to see additional information in the health report and additional messages during failover\&.
MODES OF OPERATION.PP
The utility supports two modes of operation\&. The default mode, running as a console, works as described above\&. An additional mode that permits you to run the utility as a daemon is provided for POSIX platforms\&.
.PP
When run as a daemon, the utility does not have interactivity\&. However, all events are written to the log file\&. You can control what is written to the log by using the
\fB\-\-report\-values\fR
option\&.
.PP
To run the utility as a daemon, use the
\fB\-\-daemon\fR
option\&. There are four commands that can be used in
\fB\-\-daemon\fR
option\&. These include:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
start
.sp
Starts the daemon\&. The
\fB\-\-log\fR
option is required\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
stop
.sp
Stops the daemon\&. If you used the option
\fB\-\-pidfile\fR, the value must be the same when starting the daemon\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
restart
.sp
Restarts the daemon\&. If you used the option
\fB\-\-pidfile\fR, the value must be the same when starting the daemon\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
nodetach
.sp
Starts the daemon, but does not detach the process from the console\&. The
\fB\-\-log\fR
option is required\&.
.RE
OPTIONS.PP
\fBmysqlfailover\fR
accepts the following command\-line options:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-help
.sp
Display a help message and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-license
.sp
Display license information and exit\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-candidates=\fIcandidate slave connections\fR
.sp
Connection information for candidate slave servers\&. Valid only with failover command\&. List multiple slaves in comma\-separated list\&.
.sp
To connect to a server, it is necessary to specify connection parameters such as the user name, host name, password, and either a port or socket\&. MySQL Utilities provides a number of ways to supply this information\&. All of the methods require specifying your choice via a command\-line option such as \-\-server, \-\-master, \-\-slave, etc\&. The methods include the following in order of most secure to least secure\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Use login\-paths from your
\&.mylogin\&.cnf
file (encrypted, not visible)\&. Example :
\fIlogin\-path\fR[:\fIport\fR][:\fIsocket\fR]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Use a configuration file (unencrypted, not visible) Note: available in release\-1\&.5\&.0\&. Example :
\fIconfiguration\-file\-path\fR[:\fIsection\fR]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Specify the data on the command\-line (unencrypted, visible)\&. Example :
\fIuser\fR[:\fIpasswd\fR]@\fIhost\fR[:\fIport\fR][:\fIsocket\fR]
.RE
.sp
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-connection\-timeout=\fIseconds\fR
.sp
Set the connection timeout for TCP and Unix socket connections for all master, slaves, and candidate slaves specified\&. This changes the connection timeout for the Connector/Python connection to the server\&. The default is 10 seconds as defined in the Connector/Python library\&. This setting may be helpful for installations with low network and server reliability\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-daemon=\fIcommand\fR
.sp
Run as a daemon\&. The
\fIcommand\fR
can be
start
(start daemon),
stop
(stop daemon),
restart
(stop then start the daemon) or
nodetach
(start but do not detach the process)\&. This option is only available for POSIX systems\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-discover\-slaves\-login=\fIuser:password\fR
.sp
At startup, query master for all registered slaves and use the user name and password specified to connect\&. Supply the user and password in the form
\fIuser\fR[:\fIpasswd\fR] or
\fIlogin\-path\fR\&. For example, \-\-discover=joe:secret uses \*(Aqjoe\*(Aq as the user and \*(Aqsecret\*(Aq as the password for each discovered slave\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-exec\-after=\fIscript\fR
.sp
Name of script to execute after failover or switchover\&. Script name may include the path\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-exec\-before=\fIscript\fR
.sp
Name of script to execute before failover or switchover\&. Script name may include the path\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-exec\-fail\-check=\fIscript\fR
.sp
Name of script to execute on each interval to invoke failover\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-exec\-post\-failover=\fIscript\fR
.sp
Name of script to execute after failover is complete and the utility has refreshed the health report\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-failover\-mode=\fImode\fR, \-f
\fImode\fR
.sp
Action to take when the master fails\&. \*(Aqauto\*(Aq = automatically fail to best slave, \*(Aqelect\*(Aq = fail to candidate list or if no candidate meets criteria fail, \*(Aqfail\*(Aq = take no action and stop when master fails\&. Default = \*(Aqauto\*(Aq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-force
.sp
Override the registration check on master for multiple instances of the console monitoring the same master\&. See notes\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-interval=\fIseconds\fR, \-i
\fIseconds\fR
.sp
Interval in seconds for polling the master for failure and reporting health\&. Default = 15 seconds\&. Minimum is 5 seconds\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-log=\fIlog_file\fR
.sp
Specify a log file to use for logging messages
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-log\-age=\fIdays\fR
.sp
Specify maximum age of log entries in days\&. Entries older than this are purged on startup\&. Default = 7 days\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-master=\fIconnection\fR
.sp
Connection information for the master server\&.
.sp
To connect to a server, it is necessary to specify connection parameters such as the user name, host name, password, and either a port or socket\&. MySQL Utilities provides a number of ways to supply this information\&. All of the methods require specifying your choice via a command\-line option such as \-\-server, \-\-master, \-\-slave, etc\&. The methods include the following in order of most secure to least secure\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Use login\-paths from your
\&.mylogin\&.cnf
file (encrypted, not visible)\&. Example :
\fIlogin\-path\fR[:\fIport\fR][:\fIsocket\fR]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Use a configuration file (unencrypted, not visible) Note: available in release\-1\&.5\&.0\&. Example :
\fIconfiguration\-file\-path\fR[:\fIsection\fR]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Specify the data on the command\-line (unencrypted, visible)\&. Example :
\fIuser\fR[:\fIpasswd\fR]@\fIhost\fR[:\fIport\fR][:\fIsocket\fR]
.RE
.sp
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-master\-fail\-retry=\fIseconds\fR
.sp
Time in seconds to wait to determine if the master is down\&. The failover check is run again when the retry delay expires\&. Can be used to introduce a longer period between when master is detected as unavailable to declaring it down\&. This option is not used with
\fB\-\-exec\-fail\-check\fR
option\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
This option was added in MySQL Utilities 1\&.6\&.4\&.
.sp .5v
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-max\-position=\fIposition\fR
.sp
Used to detect slave delay\&. The maximum difference between the master\*(Aqs log position and the slave\*(Aqs reported read position of the master\&. A value greater than this means the slave is too far behind the master\&. Default = 0\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-pedantic, \-p
.sp
Used to stop failover if some inconsistencies are found, such as errant transactions on slaves or SQL thread errors, during server checks\&. By default, the utility only generates warnings if issues are found when checking a slave\*(Aqs status during failover, and it continues execution unless this option is specified\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-pidfile=\fIpidfile\fR
.sp
Pidfile for running
\fBmysqlfailover\fR
as a daemon\&. This file contains the PID (process identifier), that uniquely identifies a process\&. It is needed to identify and control the process forked by
\fBmysqlfailover\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-ping=\fInumber\fR
.sp
The code uses three attempts to contact the server with the ping command as part of the detection algorithm to check to see if the master is alive\&. This option sets the number of seconds to wait between each ping attempt\&. The default
\fB\-\-ping\fR
value is 3 seconds\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
On some platforms, this is the same as number of seconds to wait for ping to return\&.
.sp .5v
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-report\-values=\fIreport_values\fR
.sp
Report values used in mysqlfailover running as a daemon\&. It can be health, gtid or uuid\&. Multiple values can be used separated by commas\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
health
.sp
Display the replication health of the topology\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
gtid
.sp
Display the master\*(Aqs list of executed GTIDs, contents of the GTID variables;
@@GLOBAL\&.GTID_EXECUTED,
@@GLOBAL\&.GTID_PURGED
and
@@GLOBAL\&.GTID_OWNED\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
uuid
.sp
Display universally unique identifiers (UUIDs) for all servers\&.
.RE
.sp
Default = health\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-rpl\-user=:\fIreplication_user\fR
.sp
The user and password for the replication user requirement, in the form:
\fIuser\fR[:\fIpassword\fR] or
\fIlogin\-path\fR\&. E\&.g\&. rpl:passwd
.sp
Default = None\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-script\-threshold=\fIreturn_code\fR
.sp
Value for external scripts to trigger aborting the operation if result is greater than or equal to the threshold\&.
.sp
Default = None (no threshold checking)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-seconds\-behind=\fIseconds\fR
.sp
Used to detect slave delay (only for health reporting purposes)\&. The maximum number of seconds behind the master permitted before slave is considered behind the master in the health report state\&. Default = 0\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-slaves=\fIslave connections\fR
.sp
Connection information for slave servers\&. List multiple slaves in comma\-separated list\&. The list is evaluated literally whereby each server is considered a slave to the master listed regardless if they are a slave of the master\&.
.sp
To connect to a server, it is necessary to specify connection parameters such as the user name, host name, password, and either a port or socket\&. MySQL Utilities provides a number of ways to supply this information\&. All of the methods require specifying your choice via a command\-line option such as \-\-server, \-\-master, \-\-slave, etc\&. The methods include the following in order of most secure to least secure\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Use login\-paths from your
\&.mylogin\&.cnf
file (encrypted, not visible)\&. Example :
\fIlogin\-path\fR[:\fIport\fR][:\fIsocket\fR]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Use a configuration file (unencrypted, not visible) Note: available in release\-1\&.5\&.0\&. Example :
\fIconfiguration\-file\-path\fR[:\fIsection\fR]
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Specify the data on the command\-line (unencrypted, visible)\&. Example :
\fIuser\fR[:\fIpasswd\fR]@\fIhost\fR[:\fIport\fR][:\fIsocket\fR]
.RE
.sp
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-ssl\-ca
.sp
The path to a file that contains a list of trusted SSL CAs\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-ssl\-cert
.sp
The name of the SSL certificate file to use for establishing a secure connection\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-ssl\-key
.sp
The name of the SSL key file to use for establishing a secure connection\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-ssl
.sp
Specifies if the server connection requires use of SSL\&. If an encrypted connection cannot be established, the connection attempt fails\&. Default setting is 0 (SSL not required)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-timeout=\fIseconds\fR
.sp
Maximum timeout in seconds to wait for each replication command to complete\&. For example, timeout for slave waiting to catch up to master\&.
.sp
Default = 3\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-verbose, \-v
.sp
Specify how much information to display\&. Use this option multiple times to increase the amount of information\&. For example,
\fB\-v\fR
= verbose,
\fB\-vv\fR
= more verbose,
\fB\-vvv\fR
= debug\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\-\-version
.sp
Display version information and exit\&.
.RE
NOTES.PP
The login user must have the appropriate permissions for the utility to check servers and monitor their status (e\&.g\&., SHOW SLAVE STATUS, SHOW MASTER STATUS)\&. The user must also have permissions to execute the failover procedure (e\&.g\&., STOP SLAVE, START SLAVE, WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS, CHANGE MASTER TO \&.\&.\&.)\&. Lastly, the user must have the REPLICATE SLAVE privilege for slaves to connect to their master\&. The same permissions are required by the failover utility for master and slaves in order to run successfully\&. In particular, users connected to slaves, candidates and master require
SUPER,
GRANT OPTION,
REPLICATION SLAVE,
RELOAD,
DROP,
CREATE,
INSERT
and
SELECT
privileges\&.
.PP
The
DROP,
CREATE,
INSERT
and
SELECT
privileges are required to register the failover instance on the initial master or the new master (after a successful failover)\&. Therefore, since any slave can become the new master, slaves and candidates also require those privileges\&. The utility checks permissions for the master, slaves, and candidates at startup\&.
.PP
Mixing IP and hostnames is not recommended\&. The replication\-specific utilities attempt to compare hostnames and IP addresses as aliases for checking slave connectivity to the master\&. However, if your installation does not support reverse name lookup, the comparison could fail\&. Without the ability to do a reverse name lookup, the replication utilities could report a false negative that the slave is (not) connected to the master\&.
.PP
For example, if you set up replication using
MASTER_HOST=ubuntu\&.net
on the slave and later connect to the slave with mysqlrplcheck and have the master specified as
\fB\-\-master=192\&.168\&.0\&.6\fR
using the valid IP address for ubuntu\&.net, you must have the ability to do a reverse name lookup to compare the IP (192\&.168\&.0\&.6) and the hostname (ubuntu\&.net) to determine if they are the same machine\&.
.PP
Similarly, in order to avoid issues mixing local IP \*(Aq127\&.0\&.0\&.1\*(Aq with \*(Aqlocalhost\*(Aq, all the addresses \*(Aq127\&.0\&.0\&.1\*(Aq are internally converted to \*(Aqlocalhost\*(Aq by the utility\&. Nevertheless, it is best to use the actual hostname of the master when connecting or setting up replication\&.
.PP
The utility checks to see if the slaves are using the option
\fB\-\-master\-info\-repository=TABLE\fR\&. If they are not, the utility stops with an error\&.
.PP
The path to the MySQL client tools should be included in the PATH environment variable in order to use the authentication mechanism with login\-paths\&. This allows the utility to use the
\fBmy_print_defaults\fR
tool which is required to read the login\-path values from the login configuration file (\&.mylogin\&.cnf)\&.
.PP
At startup, the console attempts to register itself with the master\&. If another console is already registered, and the failover mode is auto or elect, the console is blocked from running failover\&. When a console quits, it unregisters itself from the master\&. If this process is broken, the user may override the registration check by using the
\fB\-\-force\fR
option\&.
.PP
The console creates a special table in the mysql database that is used to keep track of which instance is communicating with the master\&. If you use the
\fB\-\-force\fR
option, the console removes the rows in this table\&. The table is constructed with:
.sp
.if n \{\
.RS 4
.\}
.nf
CREATE TABLE IF NOT EXISTS mysql\&.failover_console (host char(30), port char(10))
.fi
.if n \{\
.RE
.\}
.PP
When the console starts, a row is inserted containing the hostname and port of the master\&. On startup, if a row matches these values, the console does not start\&. If you use the
\fB\-\-force\fR
option, the row is deleted\&.
.PP
When running the utility using the
\fB\-\-daemon=nodetach\fR
option, the
\fB\-\-pidfile\fR
option can be omitted\&. It is ignored if used\&.
.PP
When using the external scripts, the following parameters are passed in the order shown\&.
.PP
Suppose you have a script
run_before\&.sh
and you specify that you want it executing before the failover is performed (using the
\fB\-\-exec\-before\fR
option)\&. Further, let us assume the master MySQL Server is using port 3306 on the host \(oqhost1\(cq and the MySQL Server that becomes the new master is using port 3308 on host \*(Aqcan_host2\*(Aq\&. The script would therefore be invoked in the following manner\&.
.sp
.if n \{\
.RS 4
.\}
.nf
% run_before\&.sh host1 3306 can_host2 3308
.fi
.if n \{\
.RE
.\}
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table\ \&5.3.\ \&External Script Parameters
.TS
allbox tab(:);
lB lB.
T{
MySQL Failover Option
T}:T{
Parameters Passed to External Script
T}
.T&
l l
l l
l l
l l
l l.
T{
\fB\-\-exec\-before\fR
T}:T{
master host, master port, candidate host, candidate port
T}
T{
\fB\-\-exec\-after\fR
T}:T{
new master host, new master port
T}
T{
\fB\-\-exec\-fail\-check\fR
T}:T{
master host, master port
T}
T{
\fB\-\-exec\-post\-failover\fR (no errors
              during failover)
T}:T{
old master host, old master port, new master host, new master port
T}
T{
\fB\-\-exec\-post\-failover\fR (errors
              during failover)
T}:T{
old master host, old master port
T}
.TE
.sp 1
EXAMPLES.PP
To launch the utility, you must specify at a minimum the
\fB\-\-master\fR
option and either the
\fB\-\-discover\-slaves\-login\fR
option or the
\fB\-\-slaves\fR
option\&. The
\fB\-\-discover\-slaves\-login\fR
option can be used in conjunction with the
\fB\-\-slaves\fR
option to specify a list of known slaves (or slaves that do not report their host and IP) and to discover any other slaves connected to the master\&.
.PP
An example of the user interface and some of the report views are shown in the following examples\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
The "GTID Executed Set" displays the first GTID listed in the
SHOW MASTER STATUS
view\&. If there are multiple GTIDs listed, the utility displays
[\&.\&.\&.]
to indicate there are additional GTIDs to view\&. You can view the complete list of GTIDs on the GTID display screens\&.
.sp .5v
.RE
.PP
The default interface displays the replication health report like the following\&. In this example the log file is enabled\&. A sample startup command is shown below:
.sp
.if n \{\
.RS 4
.\}
.nf
shell> \fBmysqlfailover \-\-master=root@localhost:3331 \-\-discover\-slaves\-login=root \-\-log=log\&.txt\fR
MySQL Replication Monitor and Failover Utility
Failover Mode = auto     Next Interval = Mon Mar 19 15:56:03 2012
Master Information
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Binary Log File   Position  Binlog_Do_DB  Binlog_Ignore_DB
mysql\-bin\&.000001  571
GTID Executed Set
2A67DE00\-2DA1\-11E2\-A711\-00764F2BE90F:1\-7 [\&.\&.\&.]
Replication Health Status
+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+
| host       | port  | role    | state  | gtid_mode  | health  |
+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+
| localhost  | 3331  | MASTER  | UP     | ON         | OK      |
| localhost  | 3332  | SLAVE   | UP     | ON         | OK      |
| localhost  | 3333  | SLAVE   | UP     | ON         | OK      |
| localhost  | 3334  | SLAVE   | UP     | ON         | OK      |
+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+
Q\-quit R\-refresh H\-health G\-GTID Lists U\-UUIDs L\-log entries
.fi
.if n \{\
.RE
.\}
.PP
Press
Q
to exit the utility,
R
to refresh the current display, and
H
returns to the replication health report\&.
.PP
Press the
G
key to show a GTID report similar to the following\&. The first page shown is the master\*(Aqs executed GTID set:
.sp
.if n \{\
.RS 4
.\}
.nf
MySQL Replication Monitor and Failover Utility
Failover Mode = auto     Next Interval = Mon Mar 19 15:59:33 2012
Master Information
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Binary Log File   Position  Binlog_Do_DB  Binlog_Ignore_DB
mysql\-bin\&.000001  571
GTID Executed Set
2A67DE00\-2DA1\-11E2\-A711\-00764F2BE90F:1\-7 [\&.\&.\&.]
Master GTID Executed Set
+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| gtid                                      |
+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| 2A67DE00\-2DA1\-11E2\-A711\-00764F2BE90F:1\-7  |
| 5503D37E\-2DB2\-11E2\-A781\-8077D4C14B33:1\-3  |
+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
Q\-quit R\-refresh H\-health G\-GTID Lists U\-UUIDs L\-log entries Up|Down\-scroll
.fi
.if n \{\
.RE
.\}
.PP
Continuing to press
G
cycles through the three GTID lists\&.
.PP
If the list is longer than the screen permits as shown in the example above, the scroll up and down help is also shown\&. In this case, press the
down arrow
key to scroll down\&.
.PP
Press
U
to view the list of UUIDs used in the topology, for example:
.sp
.if n \{\
.RS 4
.\}
.nf
MySQL Replication Monitor and Failover Utility
Failover Mode = auto     Next Interval = Mon Mar 19 16:02:34 2012
Master Information
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Binary Log File   Position  Binlog_Do_DB  Binlog_Ignore_DB
mysql\-bin\&.000001  571
GTID Executed Set
2A67DE00\-2DA1\-11E2\-A711\-00764F2BE90F:1\-7 [\&.\&.\&.]
UUIDs
+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| host       | port  | role    | uuid                                  |
+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
| localhost  | 3331  | MASTER  | 55c65a00\-71fd\-11e1\-9f80\-ac64ef85c961  |
| localhost  | 3332  | SLAVE   | 5dd30888\-71fd\-11e1\-9f80\-dc242138b7ec  |
| localhost  | 3333  | SLAVE   | 65ccbb38\-71fd\-11e1\-9f80\-bda8146bdb0a  |
| localhost  | 3334  | SLAVE   | 6dd6abf4\-71fd\-11e1\-9f80\-d406a0117519  |
+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
Q\-quit R\-refresh H\-health G\-GTID Lists U\-UUIDs L\-log entries
.fi
.if n \{\
.RE
.\}
.PP
If, once the master is detected as down and failover mode is auto or elect and there are viable candidate slaves, the failover feature engages automatically and the user sees the failover messages appear\&. When failover is complete, the interface returns to monitoring replication health after 5 seconds\&. The following shows an example of failover occurring:
.sp
.if n \{\
.RS 4
.\}
.nf
Failover starting\&.\&.\&.
# Candidate slave localhost:3332 will become the new master\&.
# Preparing candidate for failover\&.
# Creating replication user if it does not exist\&.
# Stopping slaves\&.
# Performing STOP on all slaves\&.
# Switching slaves to new master\&.
# Starting slaves\&.
# Performing START on all slaves\&.
# Checking slaves for errors\&.
# Failover complete\&.
# Discovering slaves for master at localhost:3332
Failover console will restart in 5 seconds\&.
.fi
.if n \{\
.RE
.\}
.PP
After the failover event, the new topology is shown in the replication health report:
.sp
.if n \{\
.RS 4
.\}
.nf
MySQL Replication Monitor and Failover Utility
Failover Mode = auto     Next Interval = Mon Mar 19 16:05:12 2012
Master Information
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Binary Log File   Position  Binlog_Do_DB  Binlog_Ignore_DB
mysql\-bin\&.000001  1117
GTID Executed Set
2A67DE00\-2DA1\-11E2\-A711\-00764F2BE90F:1\-7 [\&.\&.\&.]
UUIDs
+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+
| host       | port  | role    | state  | gtid_mode  | health  |
+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+
| localhost  | 3332  | MASTER  | UP     | ON         | OK      |
| localhost  | 3333  | SLAVE   | UP     | ON         | OK      |
| localhost  | 3334  | SLAVE   | UP     | ON         | OK      |
+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-+
Q\-quit R\-refresh H\-health G\-GTID Lists U\-UUIDs L\-log entries
.fi
.if n \{\
.RE
.\}
.PP
Pressing
L
with the
\fB\-\-log\fR
option specified causes the interface to show the entries in the log file, such as:
.sp
.if n \{\
.RS 4
.\}
.nf
MySQL Replication Monitor and Failover Utility
Failover Mode = auto     Next Interval = Mon Mar 19 16:06:13 2012
Master Information
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Binary Log File   Position  Binlog_Do_DB  Binlog_Ignore_DB
mysql\-bin\&.000001  1117
GTID Executed Set
2A67DE00\-2DA1\-11E2\-A711\-00764F2BE90F:1\-7 [\&.\&.\&.]
Log File
+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- \&.\&.\&. \-\-+
| Date                    | Entry                                    \&.\&.\&.   |
+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- \&.\&.\&. \-\-+
| 2012\-03\-19 15:55:33 PM  | INFO Failover console started\&.           \&.\&.\&.   |
| 2012\-03\-19 15:55:33 PM  | INFO Failover mode = auto\&.               \&.\&.\&.   |
| 2012\-03\-19 15:55:33 PM  | INFO Getting health for master: localhos \&.\&.\&.   |
| 2012\-03\-19 15:55:33 PM  | INFO Master status: binlog: mysql\-bin\&.00 \&.\&.\&.   |
+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- \&.\&.\&. \-\-+
Q\-quit R\-refresh H\-health G\-GTID Lists U\-UUIDs L\-log entries Up|Down\-scroll\e
.fi
.if n \{\
.RE
.\}
.sp
LIMITATIONS.PP
When the
\fB\-\-master\-fail\-retry\fR
option is used, and the value specified exceeds the value of the
\fB\-\-interval\fR
option, it is possible for an interval event to be delayed if the master retry check is still processing\&. In this case, should the master not be down, the next interval occurs immediately after the check of the master is complete\&.
PERMISSIONS REQUIRED.PP
The user must have permissions to monitor the servers on the topology and configure replication to successfully perform the failover operation\&. Additional permissions are also required to register and unregister the running mysqlfailover instance on the master and slaves\&. Specifically, the login user must have the following privileges:
SUPER,
GRANT OPTION,
REPLICATION SLAVE,
RELOAD,
DROP,
CREATE,
INSERT, and
SELECT\&. (See
\m[blue]\fBPrivileges Provided by MySQL\fR\m[]\&\s-2\u[2]\d\s+2, for more information about these\&.)
.PP
The referred permissions are required for the login users used for all servers (master, slaves, and candidates)\&.
.SH "COPYRIGHT"
.br
.PP
Copyright \(co 2006, 2017, Oracle and/or its affiliates. All rights reserved.
.PP
This documentation is free software; you can redistribute it and/or modify it only under the terms of the GNU General Public License as published by the Free Software Foundation; version 2 of the License.
.PP
This documentation is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with the program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA or see http://www.gnu.org/licenses/.
.sp
.SH "NOTES"
.IP " 1." 4
Replication with Global Transaction Identifiers
.RS 4
\%http://dev.mysql.com/doc/refman/5.7/en/replication-gtids.html
.RE
.IP " 2." 4
Privileges Provided by MySQL
.RS 4
\%http://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html
.RE
.SH "SEE ALSO"
For more information, please refer to the MySQL Utilities and Fabric
documentation, which is available online at
http://dev.mysql.com/doc/index-utils-fabric.html
.SH AUTHOR
Oracle Corporation (http://dev.mysql.com/).
